export enum BookingReservationStatuses {
  FORCOMPLETINGINVOICE = 'FOR COMPLETING INVOICE',
  FORAMENDMENT = 'FOR AMENDMENT',
  FORPAYMENT = 'FOR PAYMENT',
  FORTAGGING = 'FOR TAGGING',
  WITHREMITTANCE = 'WITH REMITTANCE',

  //Remarks Statuses
  INVOICERETURNTOTA = 'INVOICE RETURN TO TA',
  FORPROCESSING = 'FOR PROCESSING',
  PAIDONTIME = 'PAID ON TIME',
  OVERDUE = 'OVERDUE',
}
